create extension if not exists pgcrypto with schema extensions;

create table if not exists public.table_cards_lobbies (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  game text not null check (game in ('hearts', 'spades', 'euchre', 'holdem')),
  target_score integer not null default 100,
  player_count integer not null check (player_count between 2 and 8),
  difficulty text not null default 'normal' check (difficulty in ('easy', 'normal', 'hard', 'expert')),
  host_name text not null,
  host_token_hash text,
  status text not null default 'lobby' check (status in ('lobby', 'playing', 'complete')),
  game_state jsonb,
  game_version bigint not null default 0,
  expires_at timestamptz not null default (now() + interval '4 hours'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.table_cards_lobbies add column if not exists difficulty text not null default 'normal';
alter table public.table_cards_lobbies add column if not exists host_token_hash text;
alter table public.table_cards_lobbies add column if not exists game_state jsonb;
alter table public.table_cards_lobbies add column if not exists game_version bigint not null default 0;
alter table public.table_cards_lobbies add column if not exists expires_at timestamptz not null default (now() + interval '4 hours');
alter table public.table_cards_lobbies drop constraint if exists table_cards_lobbies_game_check;
alter table public.table_cards_lobbies add constraint table_cards_lobbies_game_check check (game in ('hearts', 'spades', 'euchre', 'holdem'));
alter table public.table_cards_lobbies drop constraint if exists table_cards_lobbies_player_count_check;
alter table public.table_cards_lobbies add constraint table_cards_lobbies_player_count_check check (player_count between 2 and 8);

create table if not exists public.table_cards_players (
  id uuid primary key default gen_random_uuid(),
  lobby_id uuid not null references public.table_cards_lobbies(id) on delete cascade,
  client_id text not null,
  seat_token_hash text,
  name text not null,
  seat_index integer not null check (seat_index between 0 and 7),
  is_cpu boolean not null default false,
  is_host boolean not null default false,
  is_ready boolean not null default false,
  difficulty text not null default 'normal' check (difficulty in ('easy', 'normal', 'hard', 'expert')),
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  unique (lobby_id, seat_index)
);

alter table public.table_cards_players add column if not exists seat_token_hash text;

create table if not exists public.table_cards_events (
  id bigint generated by default as identity primary key,
  lobby_id uuid not null references public.table_cards_lobbies(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists table_cards_lobbies_active_idx
  on public.table_cards_lobbies (updated_at desc)
  where status in ('lobby', 'playing');
create index if not exists table_cards_players_lobby_idx
  on public.table_cards_players (lobby_id, seat_index);
create index if not exists table_cards_events_lobby_idx
  on public.table_cards_events (lobby_id, id desc);

alter table public.table_cards_lobbies enable row level security;
alter table public.table_cards_players enable row level security;
alter table public.table_cards_events enable row level security;

drop policy if exists "Anyone can read table card lobbies" on public.table_cards_lobbies;
drop policy if exists "Anyone can create table card lobbies" on public.table_cards_lobbies;
drop policy if exists "Anyone can update table card lobbies by code" on public.table_cards_lobbies;
drop policy if exists "Anyone can read table card players" on public.table_cards_players;
drop policy if exists "Anyone can join table card lobbies" on public.table_cards_players;
drop policy if exists "Anyone can update their table card seat preview" on public.table_cards_players;
drop policy if exists "Anyone can leave a table card seat" on public.table_cards_players;
drop policy if exists "Anyone can read table card events" on public.table_cards_events;
drop policy if exists "Anyone can write table card events" on public.table_cards_events;

create policy "Public can read active Lunch Cards lobbies"
on public.table_cards_lobbies for select to anon, authenticated
using (expires_at > now());

create policy "Public can read Lunch Cards seats"
on public.table_cards_players for select to anon, authenticated
using (exists (
  select 1 from public.table_cards_lobbies lobby
  where lobby.id = lobby_id and lobby.expires_at > now()
));

create policy "Public can read Lunch Cards events"
on public.table_cards_events for select to anon, authenticated
using (exists (
  select 1 from public.table_cards_lobbies lobby
  where lobby.id = lobby_id and lobby.expires_at > now()
));

revoke all on public.table_cards_lobbies from anon, authenticated;
revoke all on public.table_cards_players from anon, authenticated;
revoke all on public.table_cards_events from anon, authenticated;
grant select (id, code, game, target_score, player_count, difficulty, host_name, status, game_version, expires_at, created_at, updated_at)
  on public.table_cards_lobbies to anon, authenticated;
grant select (id, lobby_id, client_id, name, seat_index, is_cpu, is_host, is_ready, difficulty, created_at, last_seen)
  on public.table_cards_players to anon, authenticated;
grant select on public.table_cards_events to anon, authenticated;

create or replace function public.table_cards_hash_token(token text)
returns text
language sql
immutable
strict
security invoker
set search_path = public, extensions
as $$ select encode(digest(token, 'sha256'), 'hex') $$;

create or replace function public.table_cards_get_lobby(p_code text, p_token text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
declare
  lobby_row public.table_cards_lobbies;
  authorized boolean := false;
  players_json jsonb;
begin
  select * into lobby_row from public.table_cards_lobbies
  where code = upper(p_code) and expires_at > now();
  if not found then return null; end if;
  if p_token is not null and length(p_token) >= 32 then
    select exists (
      select 1 from public.table_cards_players
      where lobby_id = lobby_row.id and seat_token_hash = public.table_cards_hash_token(p_token)
    ) into authorized;
  end if;
  select coalesce(jsonb_agg(to_jsonb(player) - 'seat_token_hash' order by player.seat_index), '[]'::jsonb)
  into players_json from public.table_cards_players player where player.lobby_id = lobby_row.id;
  return jsonb_build_object(
    'lobby', (to_jsonb(lobby_row) - 'host_token_hash' - 'game_state') ||
      jsonb_build_object('game_state', case when authorized then lobby_row.game_state else null end),
    'players', players_json
  );
end;
$$;

create or replace function public.table_cards_create_lobby(
  p_code text,
  p_game text,
  p_target integer,
  p_player_count integer,
  p_difficulty text,
  p_host_name text,
  p_client_id text,
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_lobby public.table_cards_lobbies;
  new_player public.table_cards_players;
  clean_name text := left(regexp_replace(trim(p_host_name), '[[:cntrl:]]', '', 'g'), 24);
begin
  if p_code !~ '^[A-Z0-9]{5,8}$' or length(p_token) < 32 or length(p_client_id) < 8 then
    raise exception 'Invalid session credentials';
  end if;
  if p_game not in ('hearts', 'spades', 'euchre', 'holdem')
     or p_difficulty not in ('easy', 'normal', 'hard', 'expert')
     or p_target not between 5 and 500
     or p_player_count not between 2 and 8
     or (p_game in ('hearts', 'spades') and p_player_count < 3)
     or (p_game = 'euchre' and p_player_count <> 4)
     or (p_game = 'holdem' and p_target < 100)
     or clean_name = '' then
    raise exception 'Invalid session setup';
  end if;

  insert into public.table_cards_lobbies (
    code, game, target_score, player_count, difficulty, host_name, host_token_hash, expires_at
  ) values (
    p_code, p_game, p_target, p_player_count, p_difficulty, clean_name,
    public.table_cards_hash_token(p_token), now() + interval '4 hours'
  ) returning * into new_lobby;

  insert into public.table_cards_players (
    lobby_id, client_id, seat_token_hash, name, seat_index, is_host, is_ready, difficulty
  ) values (
    new_lobby.id, p_client_id, public.table_cards_hash_token(p_token), clean_name, 0, true, true, p_difficulty
  ) returning * into new_player;

  return jsonb_build_object('lobby_id', new_lobby.id, 'player_id', new_player.id, 'seat_index', 0);
end;
$$;

create or replace function public.table_cards_join_lobby(
  p_code text,
  p_name text,
  p_client_id text,
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  target_lobby public.table_cards_lobbies;
  existing_player public.table_cards_players;
  new_player public.table_cards_players;
  open_seat integer;
  clean_name text := left(regexp_replace(trim(p_name), '[[:cntrl:]]', '', 'g'), 24);
  token_hash text := public.table_cards_hash_token(p_token);
begin
  if length(p_token) < 32 or length(p_client_id) < 8 or clean_name = '' then
    raise exception 'Invalid player credentials';
  end if;

  select * into target_lobby from public.table_cards_lobbies
  where code = upper(p_code) for update;
  if not found or target_lobby.status <> 'lobby' or target_lobby.expires_at <= now() then
    raise exception 'Session is not joinable';
  end if;

  select * into existing_player from public.table_cards_players
  where lobby_id = target_lobby.id and seat_token_hash = token_hash;
  if found then
    update public.table_cards_players set name = clean_name, client_id = p_client_id, last_seen = now()
    where id = existing_player.id returning * into existing_player;
    return to_jsonb(existing_player);
  end if;

  select seat_index into open_seat from public.table_cards_players
  where lobby_id = target_lobby.id and is_cpu
  order by seat_index limit 1;
  if open_seat is not null then
    delete from public.table_cards_players where lobby_id = target_lobby.id and seat_index = open_seat;
  else
    select candidate into open_seat
    from generate_series(0, target_lobby.player_count - 1) candidate
    where not exists (
      select 1 from public.table_cards_players player
      where player.lobby_id = target_lobby.id and player.seat_index = candidate
    )
    order by candidate limit 1;
  end if;
  if open_seat is null then raise exception 'Session is full'; end if;

  insert into public.table_cards_players (
    lobby_id, client_id, seat_token_hash, name, seat_index, is_ready, difficulty
  ) values (
    target_lobby.id, p_client_id, token_hash, clean_name, open_seat, false, target_lobby.difficulty
  ) returning * into new_player;
  update public.table_cards_lobbies set updated_at = now(), expires_at = now() + interval '4 hours'
  where id = target_lobby.id;
  return to_jsonb(new_player);
end;
$$;

create or replace function public.table_cards_update_player(
  p_code text,
  p_token text,
  p_name text default null,
  p_ready boolean default null
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  player_id uuid;
  lobby_id_value uuid;
  clean_name text;
begin
  select player.id, player.lobby_id into player_id, lobby_id_value
  from public.table_cards_players player
  join public.table_cards_lobbies lobby on lobby.id = player.lobby_id
  where lobby.code = upper(p_code)
    and player.seat_token_hash = public.table_cards_hash_token(p_token)
    and lobby.status = 'lobby';
  if player_id is null then raise exception 'Seat is not editable'; end if;

  if p_name is not null then
    clean_name := left(regexp_replace(trim(p_name), '[[:cntrl:]]', '', 'g'), 24);
    if clean_name = '' then raise exception 'Name is required'; end if;
  end if;
  update public.table_cards_players
  set name = coalesce(clean_name, name), is_ready = coalesce(p_ready, is_ready), last_seen = now()
  where id = player_id;
  update public.table_cards_lobbies
  set host_name = case when host_token_hash = public.table_cards_hash_token(p_token) and clean_name is not null then clean_name else host_name end,
      updated_at = now(), expires_at = now() + interval '4 hours'
  where id = lobby_id_value;
  return true;
end;
$$;

create or replace function public.table_cards_update_lobby(
  p_code text,
  p_token text,
  p_game text,
  p_target integer,
  p_player_count integer,
  p_difficulty text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  target_lobby public.table_cards_lobbies;
  highest_human_seat integer;
begin
  select * into target_lobby from public.table_cards_lobbies
  where code = upper(p_code) and host_token_hash = public.table_cards_hash_token(p_token)
  for update;
  if not found or target_lobby.status <> 'lobby' then raise exception 'Host access required'; end if;
  if p_game not in ('hearts', 'spades', 'euchre', 'holdem')
     or p_difficulty not in ('easy', 'normal', 'hard', 'expert')
     or p_target not between 5 and 500
     or p_player_count not between 2 and 8
     or (p_game in ('hearts', 'spades') and p_player_count < 3)
     or (p_game = 'euchre' and p_player_count <> 4)
     or (p_game = 'holdem' and p_target < 100) then
    raise exception 'Invalid session setup';
  end if;
  select max(seat_index) into highest_human_seat from public.table_cards_players
  where lobby_id = target_lobby.id and not is_cpu;
  if coalesce(highest_human_seat, 0) >= p_player_count then
    raise exception 'A coworker occupies a seat outside the new table size';
  end if;
  delete from public.table_cards_players
  where lobby_id = target_lobby.id and is_cpu and seat_index >= p_player_count;
  update public.table_cards_players set difficulty = p_difficulty
  where lobby_id = target_lobby.id and is_cpu;
  update public.table_cards_lobbies
  set game = p_game, target_score = p_target, player_count = p_player_count,
      difficulty = p_difficulty, updated_at = now(), expires_at = now() + interval '4 hours'
  where id = target_lobby.id;
  return true;
end;
$$;

create or replace function public.table_cards_fill_cpus(p_code text, p_token text)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  target_lobby public.table_cards_lobbies;
  inserted_count integer := 0;
  seat integer;
begin
  select * into target_lobby from public.table_cards_lobbies
  where code = upper(p_code) and host_token_hash = public.table_cards_hash_token(p_token)
  for update;
  if not found or target_lobby.status <> 'lobby' then raise exception 'Host access required'; end if;
  for seat in 0..target_lobby.player_count - 1 loop
    if not exists (select 1 from public.table_cards_players where lobby_id = target_lobby.id and seat_index = seat) then
      insert into public.table_cards_players (
        lobby_id, client_id, name, seat_index, is_cpu, is_ready, difficulty
      ) values (
        target_lobby.id, 'cpu-' || target_lobby.code || '-' || seat,
        'CPU ' || seat, seat, true, true, target_lobby.difficulty
      );
      inserted_count := inserted_count + 1;
    end if;
  end loop;
  update public.table_cards_lobbies set updated_at = now(), expires_at = now() + interval '4 hours'
  where id = target_lobby.id;
  return inserted_count;
end;
$$;

create or replace function public.table_cards_start_game(p_code text, p_token text, p_state jsonb)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  target_lobby public.table_cards_lobbies;
  occupied integer;
  ready integer;
begin
  select * into target_lobby from public.table_cards_lobbies
  where code = upper(p_code) and host_token_hash = public.table_cards_hash_token(p_token)
  for update;
  if not found or target_lobby.status <> 'lobby' then raise exception 'Host access required'; end if;
  select count(*), count(*) filter (where is_ready) into occupied, ready
  from public.table_cards_players where lobby_id = target_lobby.id;
  if occupied <> target_lobby.player_count or ready <> occupied then
    raise exception 'Every seat must be filled and ready';
  end if;
  if jsonb_typeof(p_state) <> 'object' or p_state ->> 'type' <> target_lobby.game then
    raise exception 'Invalid game state';
  end if;
  update public.table_cards_lobbies
  set status = 'playing', game_state = p_state, game_version = 1,
      updated_at = now(), expires_at = now() + interval '4 hours'
  where id = target_lobby.id;
  insert into public.table_cards_events (lobby_id, event_type, payload)
  values (target_lobby.id, 'game_started', jsonb_build_object('game', target_lobby.game));
  return 1;
end;
$$;

create or replace function public.table_cards_update_game(
  p_code text,
  p_token text,
  p_expected_version bigint,
  p_state jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  target_lobby public.table_cards_lobbies;
  actor public.table_cards_players;
  actor_index integer;
  phase text;
  host_actor boolean;
  next_version bigint;
begin
  select * into target_lobby from public.table_cards_lobbies
  where code = upper(p_code) for update;
  if not found or target_lobby.status <> 'playing' or target_lobby.expires_at <= now() then
    raise exception 'Game is not active';
  end if;
  select * into actor from public.table_cards_players
  where lobby_id = target_lobby.id and seat_token_hash = public.table_cards_hash_token(p_token);
  if not found then raise exception 'Seat access required'; end if;
  if target_lobby.game_version <> p_expected_version then return -1; end if;
  if jsonb_typeof(p_state) <> 'object'
     or p_state ->> 'type' <> target_lobby.game
     or jsonb_array_length(p_state -> 'players') <> target_lobby.player_count then
    raise exception 'Invalid game state';
  end if;

  phase := target_lobby.game_state ->> 'phase';
  host_actor := target_lobby.host_token_hash = public.table_cards_hash_token(p_token);
  actor_index := case
    when phase = 'trump' then (target_lobby.game_state ->> 'currentBidder')::integer
    else (target_lobby.game_state ->> 'current')::integer
  end;
  if phase not in ('passing', 'received', 'roundover', 'gameover', 'collecting', 'poker-showdown')
     and actor.seat_index <> actor_index
     and not (host_actor and coalesce((target_lobby.game_state -> 'players' -> actor_index ->> 'cpu')::boolean, false)) then
    raise exception 'It is not this seat''s turn';
  end if;
  if phase in ('roundover', 'gameover', 'poker-showdown') and not host_actor then
    raise exception 'Only the host can advance the match';
  end if;

  next_version := target_lobby.game_version + 1;
  update public.table_cards_lobbies
  set game_state = p_state, game_version = next_version,
      status = case when p_state ->> 'phase' = 'gameover' then 'complete' else status end,
      updated_at = now(), expires_at = now() + interval '4 hours'
  where id = target_lobby.id;
  return next_version;
end;
$$;

create or replace function public.table_cards_leave_lobby(p_code text, p_token text)
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  target_lobby public.table_cards_lobbies;
  actor public.table_cards_players;
begin
  select * into target_lobby from public.table_cards_lobbies where code = upper(p_code) for update;
  if not found then return 'missing'; end if;
  select * into actor from public.table_cards_players
  where lobby_id = target_lobby.id and seat_token_hash = public.table_cards_hash_token(p_token);
  if not found then return 'missing'; end if;
  if actor.is_host then
    update public.table_cards_lobbies set status = 'complete', expires_at = now(), updated_at = now()
    where id = target_lobby.id;
    return 'closed';
  end if;
  if target_lobby.status = 'lobby' then
    delete from public.table_cards_players where id = actor.id;
    update public.table_cards_lobbies set updated_at = now() where id = target_lobby.id;
    return 'left';
  end if;
  return 'playing';
end;
$$;

create or replace function public.table_cards_heartbeat(p_code text, p_token text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  lobby_id_value uuid;
begin
  select player.lobby_id into lobby_id_value
  from public.table_cards_players player
  join public.table_cards_lobbies lobby on lobby.id = player.lobby_id
  where lobby.code = upper(p_code)
    and player.seat_token_hash = public.table_cards_hash_token(p_token)
    and lobby.status in ('lobby', 'playing');
  if lobby_id_value is null then return false; end if;
  update public.table_cards_players set last_seen = now()
  where lobby_id = lobby_id_value and seat_token_hash = public.table_cards_hash_token(p_token);
  update public.table_cards_lobbies set expires_at = now() + interval '4 hours'
  where id = lobby_id_value;
  return true;
end;
$$;

revoke all on function public.table_cards_hash_token(text) from public;
revoke all on function public.table_cards_get_lobby(text, text) from public;
revoke all on function public.table_cards_create_lobby(text, text, integer, integer, text, text, text, text) from public;
revoke all on function public.table_cards_join_lobby(text, text, text, text) from public;
revoke all on function public.table_cards_update_player(text, text, text, boolean) from public;
revoke all on function public.table_cards_update_lobby(text, text, text, integer, integer, text) from public;
revoke all on function public.table_cards_fill_cpus(text, text) from public;
revoke all on function public.table_cards_start_game(text, text, jsonb) from public;
revoke all on function public.table_cards_update_game(text, text, bigint, jsonb) from public;
revoke all on function public.table_cards_leave_lobby(text, text) from public;
revoke all on function public.table_cards_heartbeat(text, text) from public;

grant execute on function public.table_cards_create_lobby(text, text, integer, integer, text, text, text, text) to anon, authenticated;
grant execute on function public.table_cards_get_lobby(text, text) to anon, authenticated;
grant execute on function public.table_cards_join_lobby(text, text, text, text) to anon, authenticated;
grant execute on function public.table_cards_update_player(text, text, text, boolean) to anon, authenticated;
grant execute on function public.table_cards_update_lobby(text, text, text, integer, integer, text) to anon, authenticated;
grant execute on function public.table_cards_fill_cpus(text, text) to anon, authenticated;
grant execute on function public.table_cards_start_game(text, text, jsonb) to anon, authenticated;
grant execute on function public.table_cards_update_game(text, text, bigint, jsonb) to anon, authenticated;
grant execute on function public.table_cards_leave_lobby(text, text) to anon, authenticated;
grant execute on function public.table_cards_heartbeat(text, text) to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'table_cards_lobbies'
  ) then
    alter publication supabase_realtime add table public.table_cards_lobbies;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'table_cards_players'
  ) then
    alter publication supabase_realtime add table public.table_cards_players;
  end if;
end;
$$;

update public.table_cards_lobbies
set status = 'complete', expires_at = now()
where host_token_hash is null and status in ('lobby', 'playing');
