create table if not exists public.table_cards_lobbies (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  game text not null check (game in ('hearts', 'spades', 'euchre')),
  target_score integer not null default 100,
  player_count integer not null check (player_count between 3 and 8),
  host_name text not null,
  status text not null default 'lobby' check (status in ('lobby', 'playing', 'complete')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.table_cards_lobbies enable row level security;

create policy "Anyone can read table card lobbies"
on public.table_cards_lobbies
for select
to anon, authenticated
using (true);

create policy "Anyone can create table card lobbies"
on public.table_cards_lobbies
for insert
to anon, authenticated
with check (
  game in ('hearts', 'spades', 'euchre')
  and player_count between 3 and 8
  and status = 'lobby'
  and length(code) between 4 and 12
);

create policy "Anyone can update table card lobbies by code"
on public.table_cards_lobbies
for update
to anon, authenticated
using (length(code) between 4 and 12)
with check (
  game in ('hearts', 'spades', 'euchre')
  and player_count between 3 and 8
  and status in ('lobby', 'playing', 'complete')
);

create table if not exists public.table_cards_events (
  id bigint generated by default as identity primary key,
  lobby_id uuid not null references public.table_cards_lobbies(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.table_cards_events enable row level security;

create policy "Anyone can read table card events"
on public.table_cards_events
for select
to anon, authenticated
using (true);

create policy "Anyone can write table card events"
on public.table_cards_events
for insert
to anon, authenticated
with check (
  length(event_type) between 1 and 80
  and exists (
    select 1
    from public.table_cards_lobbies
    where table_cards_lobbies.id = table_cards_events.lobby_id
  )
);

create table if not exists public.table_cards_players (
  id uuid primary key default gen_random_uuid(),
  lobby_id uuid not null references public.table_cards_lobbies(id) on delete cascade,
  client_id text,
  name text not null,
  seat_index integer not null,
  is_cpu boolean not null default false,
  is_host boolean not null default false,
  is_ready boolean not null default false,
  difficulty text not null default 'normal' check (difficulty in ('easy', 'normal', 'hard', 'expert')),
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  unique (lobby_id, seat_index)
);

alter table public.table_cards_players enable row level security;

create policy "Anyone can read table card players"
on public.table_cards_players
for select
to anon, authenticated
using (true);

create policy "Anyone can join table card lobbies"
on public.table_cards_players
for insert
to anon, authenticated
with check (
  seat_index between 0 and 7
  and difficulty in ('easy', 'normal', 'hard', 'expert')
  and exists (
    select 1
    from public.table_cards_lobbies
    where table_cards_lobbies.id = table_cards_players.lobby_id
      and table_cards_lobbies.status = 'lobby'
  )
);

create policy "Anyone can update their table card seat preview"
on public.table_cards_players
for update
to anon, authenticated
using (
  exists (
    select 1
    from public.table_cards_lobbies
    where table_cards_lobbies.id = table_cards_players.lobby_id
  )
)
with check (
  seat_index between 0 and 7
  and difficulty in ('easy', 'normal', 'hard', 'expert')
);

create policy "Anyone can leave a table card seat"
on public.table_cards_players
for delete
to anon, authenticated
using (
  is_host = false
  and exists (
    select 1
    from public.table_cards_lobbies
    where table_cards_lobbies.id = table_cards_players.lobby_id
      and table_cards_lobbies.status = 'lobby'
  )
);
